### PR TITLE
core: get rid of termios2, use termios on Linux

### PR DESCRIPTION
**Pull request by julianoes**
In order to simplify and to enable the build in manylinux1 it makes sense to go back to termios instead of termios2.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Do we lose something by doing that? e.g. the ability to use non-standard baudrates?

**Comment by julianoes** [comment]
I don't think so.

**Comment by julianoes** [comment]
Tested this on Linux and baudrate change doesn't seem to be working anymore. Needs more investigation.

**Comment by julianoes** [comment]
Tested on Linux and macOS, now works for both.

**Comment by JonasVautherin** [comment]
> [  FAILED  ] CurlTest.Curl_DownloadText_HTTPS_Success

Seems to me like it is failing on appveyor, and only in Debug, because of an unrelated curl test.

**Pull request merged**
