### PR TITLE
Jenkins enable CCACHE, post cleanup, and add ninja-build to docker

### PR DESCRIPTION
**Pull request by dagar**
Here are a few minor things that might help improve build times on Jenkins.

### CODE REVIEW

**Comment by dagar** [comment]
I'll add ninja-build and ccache to the containers separately.  https://github.com/Dronecode/DronecodeSDK/pull/649

**Comment by dagar** [comment]
TODO: put ccache links on PATH.

**Comment by julianoes** [comment]
> TODO: put ccache links on PATH.

Are you sure that's what's wrong? Because locally it works, I think it's just the Jenkins docker cache because I accidentally pushed to this tag without ccache first. I can push to a new tag and try again.

**Comment by dagar** [comment]
Yes, to actually be active it needs to be the first thing in the path like this (or explicitly handled by the build system).
https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_base#L81

image

**Comment by dagar** [comment]
Safe to merge now, but won't have a big impact until we do another pass to enable CCACHE.

**Comment by dagar** [comment]
Actually, here's another way to do it via cmake. fba0855e55f5c

**Comment by julianoes** [comment]
> Actually, here's another way to do it via cmake. fba0855

Unfortunately that doesn't work on travis:
`ccache: error: Failed to create directory /home/user/.ccache/tmp: Permission denied`

**Comment by dagar** [comment]
One last thing to note is that we're still only getting CCACHE for the SDK build itself. Setting it up on the system path would also catch the dependencies, which I think is where you spent the majority of the build time.

**Comment by julianoes** [comment]
Which dependency would that be? Because they get built from the same CMakeLists.txt...

**Pull request merged**
