### PR TITLE
[wip] git: contributor and organization map

### PR DESCRIPTION
**Pull request by mrpollo**
initial dump from PX4/QGC mailmap/orgmap, there's a simple way to test this (using one year as data sample)

Contributor list (clean)
```
git log --pretty='%aN <%aE>' --since="1 year" | sort | uniq -c | sort -rn

 739 Julian Oes <julian@oes.ch>
 202 Jonas Vautherin <jonas.vautherin@gmail.com>
 177 Prashanth Shakthi <shakthi.prashanth.m@intel.com>
  28 Hamish Willee <hamishwillee@gmail.com>
  19 Dave Bowerman <david.bowerman@gmail.com>
  12 Ritul Jasuja <ritul.jasuja@intel.com>
  11 Dennis Mannhart <dennis@yuneecresearch.com>
   7 Beat Küng <beat-kueng@gmx.net>
   6 Mohamed Abdelkader Zahana <mohamedashraf123@gmail.com>
   2 Sushma Sathyanarayana <sush.satyan@gmail.com>
   1 xgerrmann <xander@gerrmann.nl>
   1 Thomas Etter <thomas.etter@auterion.com>
   1 Ramón Roche <mrpollo@gmail.com>
   1 Matthias Grob <maetugr@gmail.com>
   1 Lalit Kumar <lalit.kumar.begani@intel.com>
   1 Gabriel Moreno <gabrielm@cs.cmu.edu>
   1 Fabian Klabacher <fklabach@gmail.com>
   1 Daniel Agar <daniel@agar.ca>
   1 Bert <b.buchholz@kitepower.nl>
   1 Avinash Reddy Palleti <avinash.reddy.palleti@intel.com>
   1 Anthony Lamping <lamping.ap@gmail.com>
```

Organization list
```
git log --pretty='%aN <%aE>' --since="1 year" | git -c mailmap.file=.organizationmap check-mailmap --stdin | sort | uniq -c | sort -rn

 751 Yuneec Research <contact@yuneecresearch.com>
 238 Auterion <contact@auterion.com>
 191 Intel <contact@intel.com>
  19 Yuneec <contact@yuneec.com>
   6 Mohamed Abdelkader Zahana <mohamedashraf123@gmail.com>
   2 Yuneec USA <contact@usa.yuneec.com>
   2 Unaffiliated <no@organization.net>
   1 xgerrmann <xander@gerrmann.nl>
   1 Gabriel Moreno <gabrielm@cs.cmu.edu>
   1 Fabian Klabacher <fklabach@gmail.com>
   1 Dronecode <contact@dronecode.com>
   1 Bert <b.buchholz@kitepower.nl>
```

### CODE REVIEW

**Comment by julianoes** [comment]
I find it a bit ugly to have all these random email addresses in here, especially since they are from PX4 and QGC when just the ones from the SDK would do.

**Comment by mrpollo** [comment]
Agreed @julianoes, how can you track your contributions as one company vs the other? how do you differentiate them?

I was basically lazy and copy/pasted from the other repos since they contained info that was valuable, but its dirty adds noise and unwanted info, I'll remove it and make sure its only listing emails we care for per repo.

**Comment by julianoes** [comment]
> Agreed @julianoes, how can you track your contributions as one company vs the other? how do you differentiate them?

Good question 🤔

**Comment by mrpollo** [comment]
Could you do it by date @julianoes ?

**Comment by julianoes** [comment]
Not sure what to do here :frowning_face:

**Pull request closed without merging**
