### PR TITLE
Add AMS (Auto Maneuver System, aka emergency descend) mode support

### PR DESCRIPTION
**Pull request by bresch**
This PR allows the SDK to trigger AMS on the flight controller introduced here:
https://github.com/PX4/Firmware/pull/11169

Example of how to use the code:

```c
// AMS
std::cout << "Engaging AMS..." << std::endl;
const Action::Result ams_result = action->auto_maneuver_system();
if (takeoff_result != Action::Result::SUCCESS) {
std::cout << ERROR_CONSOLE_TEXT << "AMS failed:" << Action::result_str(ams_result)
<< NORMAL_CONSOLE_TEXT << std::endl;
return 1;
}
```

### CODE REVIEW

**Comment by julianoes** [comment]
Thanks for the pull request.

Is this AMS thing upstream? Because I'm looking at https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h and I don't see it there.

**Comment by julianoes** [comment]
@bresch please follow up.

**Comment by julianoes** [comment]
@bresch bump :smile:

**Comment by JonasVautherin** [comment]
I updated the branch and fixed style, but the CI is still failing because the documentation is lacking fields.

**Comment by julianoes** [comment]
Thanks but also this is not in upstream yet anyway, so I'm confused how it even works.

**Comment by bresch** [comment]
Sorry I'm not really responsive here... It's not merged yet in the firmware because of some changes in the `mission_item`. I'll come to you @julianoes to discuss about that.

**Comment by julianoes** [comment]
Ok, this needs to wait for the PX4 change to be merged first then.

**Comment by julianoes** [comment]
Please re-open when it is merged in PX4 and we should consider it again.

**Pull request closed without merging**
