### PR TITLE
Add configuration option

### PR DESCRIPTION
**Pull request by julianoes**
This adds a configuration option in order to set the system and component ID of the SDK, as well as correctly set the MAV_TYPE.

FYI @bkueng @cmic0.

### CODE REVIEW

**Comment by RomanBapst** [comment]
@julianoes @JonasVautherin Is this good to go?

**Comment by julianoes** [comment]
Needs testing by @cmic0.

**Comment by RomanBapst** [comment]
@julianoes I did test it and it worked. According to @cmic0 he still need to do changes on the firmware side when running avoidance.

**Comment by julianoes** [comment]
@RomanBapst great thanks.

**Comment by RomanBapst** [comment]
image

**Pull request merged**
