### PR TITLE
issue#609: only send heartbeat after discovering vehicles

### PR DESCRIPTION
**Pull request by snail914**
My first pr to open source project.  Picked from github issues tagged with `beginner`  
 
**Fixes** #609 

Another solution is to invoke `_parent.is_connected()`  inside `SystemImpl::send_heartbeat()`, which I less preferred: only need to send heartbeats when the system is connected to remote devices. But let the project owner decide :) 

Tested with integration test `AUTOSTART_SITL=1 make run_integration_tests`: 

Before: 
```
[09:29:27|Info ] DronecodeSDK version: 0.14.1 (dronecode_sdk_impl.cpp:25)
[09:29:29|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
[09:29:29|Error] No known remotes (udp_connection.cpp:130)
[09:29:29|Error] send fail (dronecode_sdk_impl.cpp:91)
Waiting to be ready...
Waiting to be ready...
[09:29:30|Error] No known remotes (udp_connection.cpp:130)
[09:29:30|Error] send fail (dronecode_sdk_impl.cpp:91)
Waiting to be ready...
```

After:
```
[09:24:25|Info ] DronecodeSDK version: 0.14.1 (dronecode_sdk_impl.cpp:25)
[09:24:27|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
Waiting to be ready...
Waiting to be ready...
Waiting to be ready...
Waiting to be ready...
```

### CODE REVIEW

**Comment by snail914** [comment]
Maybe something like this is better then
```
if (_parent.is_connected() && 
    _time.elapsed_since_s(last_time) >= SystemImpl::_HEARTBEAT_SEND_INTERVAL_S) {
{
     send_heartbeat();
     last_time = _time.steady_time();
}
// else, go to next iteration
```

**Comment by snail914** [comment]
Nah,, still need optimization....

**Comment by julianoes** [comment]
Yes, I think that should be fine, no?

**Comment by snail914** [comment]
Yes, that works as expected only if the remote devices are online after the first `SystemImpl::_HEARTBEAT_SEND_INTERVAL_S`  seconds. 

If the remotes devices are connected before  the first `SystemImpl::_HEARTBEAT_SEND_INTERVAL_S` when the system is started,  then the system still need to wait  `SystemImpl::_HEARTBEAT_SEND_INTERVAL_S`  to send the first heartbeat. 

Not familiar with your user contract.  But maybe this is already enough optimized?

**Comment by julianoes** [comment]
Hm, do you see a disadvantage of putting the `_last_time ...` inside the if

**Comment by julianoes** [comment]
Sorry for the late response here. Let me merge this and then optimize it later.

**Comment by hamishwillee** [comment]
@julianoes Note, next MAVLink meeting, I hope you will be a bit able to talk about connection semantics, as discussed 2 meetings ago. Specifically, the theory is that every component should broadcast it's heartbeat even if it hasn't found something else, and you pointed out that GCS has no standard place to broadcast.

**Pull request merged**
