### PR TITLE
[WIP] Update to new UUID

### PR DESCRIPTION
**Pull request by julianoes**
At some point we need to update to the new UUID (`uid2`) mavlink field.

This is an old branch where I started this.

### CODE REVIEW

**Comment by julianoes** [comment]
I'm tempted to scrap this and just use the MAVLink system ID 1-255 instead of the complicated UID addressing.

**Comment by hamishwillee** [comment]
I can see why. The only value in it is that you can write code that is resistant to the case where people change Sys ID on a system, and in future we could move to a different transport than MAVLink. For the former the benefits seem minimal for the complication, and for the later we'd probably rethink  a lot of things anyway.

**Comment by julianoes** [comment]
Right but we don't have that now. And this UID only works for autopilots but not form companion computers, cameras, etc. anyway.

**Comment by hamishwillee** [comment]
Yes. So if I was the boss, we would move to just SysIds.

**Pull request closed without merging**
