### PR TITLE
Jenkinsfile: update to latest docker tag

### PR DESCRIPTION
**Pull request by julianoes**
This includes sudo.

This is a follow up to #557.

### CODE REVIEW

**Comment by julianoes** [comment]
@dbowerman do you know why travis-ci ends up without permission:
https://travis-ci.org/Dronecode/DronecodeSDK/jobs/432376354#L575-L577

**Comment by dbowerman** [comment]
@julianoes only that somehow $TRAVIS_BUILD_DIR at that point is not valid. ie the container mounted some dud directory.

**Comment by JonasVautherin** [comment]
@julianoes: About the examples, I believe that it should be possible to build them without `sudo`:

1. Install the SDK locally (using `INSTALL_PREFIX`).
2. Build examples with `CPLUS_INCLUDE_PATH=/path/to/installed/include` and `LIBRARY_PATH=/path/to/installed/lib`.
3. Run the examples (possibly with `LD_LIBRARY_PATH`, but I'm not even sure that's necessary here).

**Comment by julianoes** [comment]
@JonasVautherin yes that would work but it means the setup is a bit different from the real use case but I guess that's ok.

**Comment by dbowerman** [comment]
Is the issue the 'user' option being passed to docker. ie. -u `stat -c "%u:%g" $TRAVIS_BUILD_DIR` ?
Inside the container the users are 'dronecode' and 'root' or more correctly 'dronecode' and 'dronecode using sudo'.

I reckon remove the -u option.

**Comment by julianoes** [comment]
I don't understand the error that now happens on Fedora:
```
dirname: missing operand
Try 'dirname --help' for more information.
/bin/sh: line 0: cd: build/default: Not a directory
Build dir: build/default
/bin/sh: line 0: cd: build/default: Not a directory
```

**Comment by julianoes** [comment]
@dbowerman the problem is that the solution with the default `dronecode` user only works if you're using docker as the user with ID 1000. For everything else you seem to run into troubles.

In my opinion the solution before with just root just worked even though it would sometimes require a `sudo make clean` to clean up.

**Comment by dbowerman** [comment]
@julianoes Ah yes. thinking about it, that makes sense. I didn't pick that because I'm the only user (usually uid 1000) on my systems. Give me a day or so to see if theres a solution, otherwise revert I guess.

**Comment by dbowerman** [comment]
@julianoes this article describes the exact problem and offers a solution.
https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
Do you want to go down that path? or revert?

**Comment by julianoes** [comment]
@dbowerman oh yes nice, that should work.

**Comment by julianoes** [comment]
@dbowerman hm, so I tried this and got:
```
Starting with UID : 9001
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
su: user user does not exist
```

**Comment by julianoes** [comment]
Note: I'm trying to come by without `gosu` for now, we'll see if that's good enough.

**Comment by JonasVautherin** [comment]
What's the status on that? I believe it is currently breaking the travis build on all the PRs, which is a bit blocking :/.

**Comment by julianoes** [comment]
Forgot to update the docker images, re-running travis.

**Comment by julianoes** [comment]
Yay, it finally passed. @JonasVautherin please review and merge, so CI is fixed.

**Comment by JonasVautherin** [comment]
Thanks!

**Pull request merged**
